-- MySQL Script generated by MySQL Workbench
-- Tue Nov 27 09:57:35 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema kylevoight
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema kylevoight
-- -----------------------------------------------------
-- CREATE SCHEMA IF NOT EXISTS `kylevoight` DEFAULT CHARACTER SET utf8 ;
USE `kylevoight` ;

-- -----------------------------------------------------
-- Table `kylevoight`.`Incident_Type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kylevoight`.`Incident_Type` ;

CREATE TABLE IF NOT EXISTS `kylevoight`.`Incident_Type` (
  `idIncident_Type` INT NOT NULL,
  `Type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idIncident_Type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kylevoight`.`Handeler`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kylevoight`.`Handeler` ;

CREATE TABLE IF NOT EXISTS `kylevoight`.`Handeler` (
  `idHandeler` INT NOT NULL,
  `emailAdress` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idHandeler`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kylevoight`.`Incident`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kylevoight`.`Incident` ;

CREATE TABLE IF NOT EXISTS `kylevoight`.`Incident` (
  `idIncident_Info` INT NOT NULL,
  `DateCreated` DATE NOT NULL,
  `IncidentState` CHAR(10) NOT NULL,
  `Incident_Type_idIncident_Type` INT NOT NULL,
  `Handeler_idHandeler` INT NOT NULL,
  PRIMARY KEY (`idIncident_Info`),
  INDEX `fk_Incident_Info_Incident_Type1_idx` (`Incident_Type_idIncident_Type` ASC) ,
  INDEX `fk_Incident_Handeler1_idx` (`Handeler_idHandeler` ASC) ,
  CONSTRAINT `fk_Incident_Info_Incident_Type`
    FOREIGN KEY (`Incident_Type_idIncident_Type`)
    REFERENCES `kylevoight`.`Incident_Type` (`idIncident_Type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Incident_Handeler1`
    FOREIGN KEY (`Handeler_idHandeler`)
    REFERENCES `kylevoight`.`Handeler` (`idHandeler`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kylevoight`.`Person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kylevoight`.`Person` ;

CREATE TABLE IF NOT EXISTS `kylevoight`.`Person` (
  `idPerson` INT NOT NULL,
  `LastName` TINYTEXT NOT NULL,
  `FirstName` TEXT(15) NOT NULL,
  `JobTitle` VARCHAR(45) NOT NULL,
  `EmailAddress` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPerson`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kylevoight`.`Incident_Person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kylevoight`.`Incident_Person` ;

CREATE TABLE IF NOT EXISTS `kylevoight`.`Incident_Person` (
  `idIncident` INT NOT NULL,
  `Person_idPerson` INT NOT NULL,
  `Incident_Info_idIncident_Info` INT NOT NULL,
  INDEX `fk_table1_Person1_idx` (`Person_idPerson` ASC) ,
  PRIMARY KEY (`idIncident`),
  INDEX `fk_Incident_Incident_Info1_idx` (`Incident_Info_idIncident_Info` ASC) ,
  CONSTRAINT `fk_table1_Person1`
    FOREIGN KEY (`Person_idPerson`)
    REFERENCES `kylevoight`.`Person` (`idPerson`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Incident_Incident_Info1`
    FOREIGN KEY (`Incident_Info_idIncident_Info`)
    REFERENCES `kylevoight`.`Incident` (`idIncident_Info`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kylevoight`.`IP_Address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kylevoight`.`IP_Address` ;

CREATE TABLE IF NOT EXISTS `kylevoight`.`IP_Address` (
  `idIP_Address` INT NOT NULL,
  `Incident_idIncident_Info` INT NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idIP_Address`, `Incident_idIncident_Info`),
  INDEX `fk_IP_Address_Incident1_idx` (`Incident_idIncident_Info` ASC) ,
  CONSTRAINT `fk_IP_Address_Incident1`
    FOREIGN KEY (`Incident_idIncident_Info`)
    REFERENCES `kylevoight`.`Incident` (`idIncident_Info`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
